CREATE OR REPLACE SCHEMA TEST_SCHEMA;

CREATE OR REPLACE TABLE TEST_SCHEMA.CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    CITY STRING
);

CREATE OR REPLACE TABLE TEST_SCHEMA.ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    AMOUNT NUMBER(10,2)
);

CREATE OR REPLACE TABLE TEST_SCHEMA.PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    PRICE NUMBER(10,2)
);
