DROP VIEW IF EXISTS TEST_SCHEMA.VW_CUSTOMER_ORDERS;

DROP VIEW IF EXISTS TEST_SCHEMA.VW_CUSTOMER_CITY;

DROP TABLE IF EXISTS TEST_SCHEMA.ORDERS;

DROP TABLE IF EXISTS TEST_SCHEMA.CUSTOMERS;

DROP SCHEMA IF EXISTS TEST_SCHEMA;
